[general]
name = "minimaxai-msa-sm121"
license = "Apache-2.0"
version = 1
backends = ["cuda"]

[general.cuda]
minver = "12.8"

[general.hub]
repo-id = "flashrt/MiniMaxAI-msa-sm121"

[torch-noarch]

[kernel]
