[general]
name = "vl-transformer-primitives"
license = "Apache-2.0"
version = 1
backends = ["cuda"]

[general.cuda]
minver = "12.8"

[general.hub]
repo-id = "flashrt/vl-transformer-primitives"

[torch]
include = ["csrc"]
src = [
  "torch-ext/torch_binding.cpp",
  "torch-ext/torch_binding.h",
]

[kernel.vl_transformer_primitives]
backend = "cuda"
depends = ["torch"]
include = ["csrc"]
cuda-minver = "12.8"
src = [
  "csrc/qwen3_qkv_post_proc.cu",
  "csrc/qwen3_qkv_post_proc.cuh",
  "csrc/avg_pool_vision_tokens.cu",
  "csrc/avg_pool_vision_tokens.cuh",
]
