[general]
name = "blockwise-fp8-producers"
license = "Apache-2.0"
version = 1
backends = ["cuda"]

[general.cuda]
minver = "12.8"

[general.hub]
repo-id = "flashrt/blockwise-fp8-producers"

[torch]
include = ["csrc"]
src = [
  "torch-ext/torch_binding.cpp",
  "torch-ext/torch_binding.h",
]

[kernel.blockwise_fp8_producers]
backend = "cuda"
depends = ["torch"]
include = ["csrc"]
cuda-minver = "12.8"
src = [
  "csrc/fp8_per_token_block_quant.cu",
  "csrc/fp8_per_token_block_quant.cuh",
  "csrc/norm_act_to_fp8_block128.cu",
  "csrc/norm_act_to_fp8_block128.cuh",
]
cuda-flags = [
  "-U__CUDA_NO_BFLOAT16_CONVERSIONS__",
  "-U__CUDA_NO_BFLOAT16_OPERATORS__",
  "-U__CUDA_NO_BFLOAT162_OPERATORS__",
]
