[general]
name = "flashrt-nvfp4"
license = "Apache-2.0"
version = 1
backends = ["cuda"]

[general.hub]
repo-id = "flashrt/flashrt-nvfp4"

[torch]
include = ["csrc"]
src = [
  "torch-ext/torch_binding.cpp",
  "torch-ext/torch_binding.h",
]

[kernel.flashrt_nvfp4]
backend = "cuda"
depends = ["torch"]
include = ["csrc"]
src = [
  "csrc/nvfp4_sf_reshape_sm120.cu",
  "csrc/nvfp4_sf_reshape_sm120.cuh",
]
