[general]
name = "flashrt-adarms-train"
license = "Apache-2.0"
version = 1
backends = ["cuda"]

[general.cuda]
minver = "12.8"

[general.hub]
repo-id = "flashrt/flashrt-adarms-train"

[torch]
include = ["csrc"]
src = [
  "torch-ext/torch_binding.cpp",
  "torch-ext/torch_binding.h",
]

[kernel.flashrt_adarms_train]
backend = "cuda"
depends = ["torch"]
include = ["csrc"]
cuda-minver = "12.8"
src = [
  "csrc/adarms_train.cu",
  "csrc/adarms_train.cuh",
]
