[general]
name = "gated-delta-attention"
license = "Apache-2.0"
version = 2
backends = ["cuda"]

[general.cuda]
minver = "12.8"

[general.hub]
repo-id = "flashrt/gated-delta-attention"

[torch]
include = ["csrc"]
src = [
  "torch-ext/torch_binding.cpp",
  "torch-ext/torch_binding.h",
]

[kernel.gated_delta_attention]
backend = "cuda"
depends = ["torch"]
include = ["csrc"]
cuda-minver = "12.8"
src = [
  "csrc/gated_delta_attention.cu",
  "csrc/gated_delta_attention.cuh",
]
cuda-flags = [
  "-U__CUDA_NO_BFLOAT16_CONVERSIONS__",
  "-U__CUDA_NO_BFLOAT16_OPERATORS__",
  "-U__CUDA_NO_BFLOAT162_OPERATORS__",
]
