#pragma once

#include <cuda_runtime.h>
#include <stdint.h>

void flashrt_xqa_bf16_fp8kv(
    const void* q,
    const void* k_cache,
    const void* v_cache,
    const int32_t* page_table,
    const uint32_t* seq_lens,
    const uint32_t* mask,
    void* out,
    uint32_t* semaphores,
    void* scratch,
    int max_seq_len,
    int q_seq_len,
    int sm_count,
    float q_scale,
    float kv_scale,
    bool enable_pdl,
    int64_t k_stride_page,
    int64_t k_stride_token,
    int64_t k_stride_head,
    cudaStream_t stream);

void flashrt_xqa_bf16_fp8kv_d128(
    const void* q,
    const void* k_cache,
    const void* v_cache,
    const int32_t* page_table,
    const uint32_t* seq_lens,
    const uint32_t* mask,
    void* out,
    uint32_t* semaphores,
    void* scratch,
    int max_seq_len,
    int q_seq_len,
    int num_kv_heads,
    int head_group_size,
    int sm_count,
    float q_scale,
    float kv_scale,
    bool enable_pdl,
    int64_t k_stride_page,
    int64_t k_stride_token,
    int64_t k_stride_head,
    cudaStream_t stream);

void flashrt_xqa_bf16_fp8kv_d256_g8(
    const void* q,
    const void* k_cache,
    const void* v_cache,
    const int32_t* page_table,
    const uint32_t* seq_lens,
    const uint32_t* mask,
    void* out,
    uint32_t* semaphores,
    void* scratch,
    int max_seq_len,
    int q_seq_len,
    int num_kv_heads,
    int sm_count,
    float q_scale,
    float kv_scale,
    bool enable_pdl,
    int64_t k_stride_page,
    int64_t k_stride_token,
    int64_t k_stride_head,
    cudaStream_t stream);
